### PR TITLE
fix: Remove block specific vars from theme #57

### LINKED ISSUE #57: Remove block specific vars from theme
Themes should not contain any block specific vars. The current set of vars that are allowed in a theme arre.

```
  --primary-color: #035fe6;
  --secondary-color: #136ff6;
  --background-color: #fff;
  --overlay-color: #eee;
  --text-color: #000;
  --text-color-background: #fff;
```

If these vars are not enough for a block to use then an issue/PR should be opened to introduce a new var to the theming system.

### PR DESCRIPTION
**Pull request by arumsey**
## Issue

Fix #57

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- After: https://block-theme--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1

## 📝 Description:

- remove stats vars from theme
- allow stats background image to come from content
- introduce new styles to control stats layout

image

image

image

image

### CODE REVIEW

File: blocks/columns/columns.js [hunk 1]
```diff
@@ -20,4 +20,14 @@ export default function decorate(block) {
       }
     });
   });
+
+  // stats background image
+  const backgroundPicture = block.querySelector(':scope > div > .columns-img-col');
```
Comment (tmathern) [inline blocks/columns/columns.js:25]: Note - I think I'll need this too (or very similar code). If I do, I'll move it into scripts and refactor.

**Review by tmathern — APPROVED** [review]

**Review by allentsliu — APPROVED** [review]
LGTM! Thanks a lot @arumsey  for fixing it!
